-- "addons\\_config\\lua\\config\\clothes.lua"
-- Retrieved by https://github.com/lewisclark/glua-steal
CFG.clothes = {
	standart1_sheet = {
		mat = 'models/humans/modern/octo/standart1_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "Gotu" ',
		desc = 'Бордовая куртка с белой футболкой, черные джинсы, белые кроссовки с синими полосами по бокам',
	},
	standart2_sheet = {
		mat = 'models/humans/modern/octo/standart2_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "Edward"',
		desc = 'Коричневая куртка с черным свитером и белой футболкой, темно-синие джинсы с кожаным ремнем и черными ботинками',
	},
	standart3_sheet = {
		mat = 'models/humans/modern/octo/standart3_sheet',
		icon = octolib.icons.color('clothes_shirt'),
		name = 'Костюм "Gentleman"',
		desc = 'Синее полупальто с белой футболкой, черные штаны, коричневые ботинки',
	},
	standart4_sheet = {
		mat = 'models/humans/modern/octo/standart4_sheet',
		icon = octolib.icons.color('clothes_shirt'),
		name = 'Костюм "Frant"',
		desc = 'Черный пиджак с серым свитером, серые джинсы, черные туфли',
	},
	standart5_sheet = {
		mat = 'models/humans/modern/octo/standart5_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Зеленая рубашка',
		desc = 'Зеленая рубашка с белой футболкой с длинным рукавом, серые штаны, коричневые ботинки',
	},
	standart6_sheet = {
		mat = 'models/humans/modern/octo/standart6_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Кожанка "Belić"',
		desc = 'Коричневая кожаная куртка с бежевой футболкой и бело-желтой олимпийкой, полуперчатки, синие штаны, белые кроссовки с синими полосками по бокам',
	},
	standart7_sheet = {
		mat = 'models/humans/modern/octo/standart7_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Кожанка "Niko"',
		desc = 'Черная кожаная куртка с синей рубашкой и бежевой футболкой, черные штаны, черные ботинки',
	},
	standart8_sheet = {
		mat = 'models/humans/modern/octo/standart8_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Костюм "Bro3s"',
		desc = 'Серая кофта с белой футболкой, штаны в раскраске "камо", коричневые ботинки',
	},
	standart9_sheet = {
		mat = 'models/humans/modern/octo/standart9_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Голубая клетчатая рубашка',
		desc = 'Клетчатая рубашка в голубых тонах с серой футболкой с длинными рукавами, бежевые джинсы, черные кроссовки с белым ободом ',
	},
	standart10_sheet = {
		mat = 'models/humans/modern/octo/standart10_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Красная клетчатая рубашка',
		desc = 'Клетчатая красная рубашка с зеленой футболкой с длинными рукавами, голубые джинсы, коричневые ботинки с белым ободом',
	},
	standart11_sheet = {
		mat = 'models/humans/modern/octo/standart11_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Байкер "Wolf"',
		desc = 'Коричневая куртка с белой футболкой, полуперчатки, серые джинсы, коричневые ботинки',
	},
	standart12_sheet = {
		mat = 'models/humans/modern/octo/standart12_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Классический байкер',
		desc = 'Черная кожаная куртка с белыми полосами, полуперчатки, синими джинсами и белыми кроссовками',
	},
	standart13_sheet = {
		mat = 'models/humans/modern/octo/standart13_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Сельский байкер',
		desc = 'Красная клетчатая рубашка с оранжевым жилетом и белой футболкой, серые джинсы, черные ботинки',
	},
	standart14_sheet = {
		mat = 'models/humans/modern/octo/standart14_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Степной байкер',
		desc = 'Зеленая клетчатая рубашка с черно-бежевым жилетом и черной футболкой, черные джинсы, коричневые ботинки',
	},
	standart15_sheet = {
		mat = 'models/humans/modern/octo/standart15_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "Arlo"',
		desc = 'Желтая кофта с черным жилетом, голубые джинсы, черные ботинки',
	},
	standart16_sheet = {
		mat = 'models/humans/modern/octo/standart16_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Джинсовый костюм',
		desc = 'Джинсовая куртка с белой футболкой, голубые джинсы, коричневые ботинки',
	},
	standart17_sheet = {
		mat = 'models/humans/modern/octo/standart17_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "CityLife"',
		desc = 'Джинсовая куртка, серый худи, синие джинсы, белые кроссовки',
	},
	standart18_sheet = {
		mat = 'models/humans/modern/octo/standart18_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "Dandy"',
		desc = 'Клетчатая рубашка в синих тонах с серой футболкой с принтом, голубые джинсы, черные кроссовки',
	},
	standart19_sheet = {
		mat = 'models/humans/modern/octo/standart19_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "Tommy"',
		desc = 'Темно-синяя толстовка с белой футболкой, синие джинсы, черные кроссовки',
	},
	standart20_sheet = {
		mat = 'models/humans/modern/octo/standart20_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Голубая поло',
		desc = 'Голубая рубашка поло, черные джинсы, черные ботинки',
	},
	standart21_sheet = {
		mat = 'models/humans/modern/octo/standart21_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Костюм "Retro"',
		desc = 'Бирюзовая олимпийка с зеленой рубашкой поло, голубые джинсы, черные ботинки',
	},
	standart22_sheet = {
		mat = 'models/humans/modern/octo/standart22_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Худи "Polo"',
		desc = 'Серая толстовка с принтом, черные джинсы, коричневые ботинки',
	},
	standart23_sheet = {
		mat = 'models/humans/modern/octo/standart23_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Худи "Nike SB"',
		desc = 'Черный худи с принтом, синие джинсы, черные кроссовки',
	},
	sport1_sheet = {
		mat = 'models/humans/modern/octo/sport1_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Худи "In The Hood"',
		desc = 'Черная кофта с белой футболкой, черные штаны, черные кроссовки',
	},
	sport2_sheet = {
		mat = 'models/humans/modern/octo/sport2_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Зеленый спортивный костюм',
		desc = 'Черно-зеленая куртка с белой футболкой, черные штаны, черные кроссовки',
	},
	sport3_sheet = {
		mat = 'models/humans/modern/octo/sport3_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Красный спортивный костюм',
		desc = 'Черно-оранжевая куртка с белой футболкой, голубые джинсы, белые кроссовки',
	},
	sport4_sheet = {
		mat = 'models/humans/modern/octo/sport4_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Костюм "Jordan"',
		desc = 'Белая кофта с символикой Jordan в центре и черной футболкой, темные брюки, оранжевые кроссовки',
	},
	sport5_sheet = {
		mat = 'models/humans/modern/octo/sport5_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Худи "Banana"',
		desc = 'Голубая кофта с изображением банана в центре и белой футболкой, коричневые штаны, белые кроссовки',
	},
	sport6_sheet = {
		mat = 'models/humans/modern/octo/sport6_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Черный спортивный костюм',
		desc = 'Черная куртка с белыми полосами на руках и белой футболкой, черные штаны, черные кроссовки',
	},
	sport7_sheet = {
		mat = 'models/humans/modern/octo/sport7_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Синий спортивный костюм',
		desc = 'Голубая куртка с белой футболкой, голубые штаны, черные кроссовки',
	},
	sport8_sheet = {
		mat = 'models/humans/modern/octo/sport8_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Костюм "Marce"',
		desc = 'Серая толстовка с белой футболкой, черные брюки, черные кроссовки',
	},
	sport9_sheet = {
		mat = 'models/humans/modern/octo/sport9_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Синий костюм Adidas',
		desc = 'Сине-голубая куртка с белой футболкой, темно-синие штаны, белые кроссовки',
	},
	sport10_sheet = {
		mat = 'models/humans/modern/octo/sport10_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Зеленый костюм Adidas',
		desc = 'Черно-зеленая куртка с белой футболкой, черные штаны, белые кроссовки',
	},
	sport11_sheet = {
		mat = 'models/humans/modern/octo/sport11_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Красный костюм Adidas',
		desc = 'Красный спортивный костюм, белые кроссовки',
	},
	sport12_sheet = {
		mat = 'models/humans/modern/octo/sport12_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Костюм "Kappa"',
		desc = 'Черный спортивный костюм с принтами по бокам, белые кроссовки',
	},
	sport13_sheet = {
		mat = 'models/humans/modern/octo/sport13_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Зеленый костюм Nike',
		desc = 'Зелено-серая куртка, белая футболка с принтом, зеленые штаны, белые кроссовки',
	},
	sport14_sheet = {
		mat = 'models/humans/modern/octo/sport14_sheet',
		icon = octolib.icons.color('clothes_tshirt'),
		name = 'Черный костюм Nike',
		desc = 'Черно-серая куртка, черная футболка с принтом, черные штаны, белые кроссовки',
	},
	suit1_sheet = {
		mat = 'models/humans/modern/octo/suit1_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Костюм "D\'Anglere"',
		desc = 'Синий деловой костюм в полосочку с белой рубашкой, красным галстуком и черными туфлями',
	},
	suit2_sheet = {
		mat = 'models/humans/modern/octo/suit2_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Черный деловой костюм',
		desc = 'Черный деловой костюм с белой рубашкой, черным галстуком и черными туфлями',
	},
	suit3_sheet = {
		mat = 'models/humans/modern/octo/suit3_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Белый деловой костюм',
		desc = 'Белый деловой костюм с черной рубашкой, желтым галстуком и черными туфлями',
	},
	suit4_sheet = {
		mat = 'models/humans/modern/octo/suit4_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Серый деловой костюм',
		desc = 'Серый деловой костюм с голубой рубашкой, желтым галстуком и серыми туфлями',
	},
	suit5_sheet = {
		mat = 'models/humans/modern/octo/suit5_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Зеленый деловой костюм',
		desc = 'Зеленый деловой костюм с белой рубашкой, зеленым галстуком и черными туфлями',
	},
	suit6_sheet = {
		mat = 'models/humans/modern/octo/suit6_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Голубой деловой костюм',
		desc = 'Голубой деловой костюм с красной рубашкой, синим галстуком и коричневыми туфлями',
	},
	suit7_sheet = {
		mat = 'models/humans/modern/octo/suit7_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Черный пиджак',
		desc = 'Черный пиджак с белой рубашкой, черные брюки и черные туфли',
	},
	suit8_sheet = {
		mat = 'models/humans/modern/octo/suit8_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Синий пиджак',
		desc = 'Синий пиджак с белой рубашкой, синие брюки и черные туфли',
	},
	clothes_dobrograd = {
		name = L.clothes_dobrograd,
		desc = L.clothes_dobrograd_desc,
		icon = octolib.icons.color('clothes_jacket'),
		mat = 'models/humans/modern/octo/dbg_city_day',
		persistent = true,
	},
	dbg_city_day2 = {
		name = 'Костюм патриота 2024',
		desc = L.clothes_dobrograd_desc,
		icon = octolib.icons.color('clothes_jacket'),
		mat = 'models/humans/modern/octo/dbg_city_day2',
		persistent = true,
	},

	-- xmas
	winter1_sheet = {
		mat = 'models/humans/modern/octo/winter1_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Зеленый свитер с оленями (мужской)',
		desc = 'Теплый мужской зеленый свитер с красными вставками, на котором красуются олени и рождественские узоры',
		gender = 'male',
		warm = true,
	},
	winter2_sheet = {
		mat = 'models/humans/modern/octo/winter2_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Коричневый свитер с оленями (мужской)',
		desc = 'Теплый мужской коричневый свитер, на котором красуются олени и рождественские узоры',
		gender = 'male',
		warm = true,
	},
	winter3_sheet = {
		mat = 'models/humans/modern/octo/winter3_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Белый свитер с оленями (мужской)',
		desc = 'Теплый мужской белый свитер, на котором красуются олени и рождественские узоры',
		gender = 'male',
		warm = true,
	},
	winter4_sheet = {
		mat = 'models/humans/modern/octo/winter4_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Черный пуховик (мужской)',
		desc = 'Черный мужской пуховик и бело-голубой теплый свитер с оленями и рождественскими узорами',
		gender = 'male',
		warm = true,
	},
	winter5_sheet = {
		mat = 'models/humans/modern/octo/winter5_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Черно-зеленый пуховик (мужской)',
		desc = 'Черно-зеленый мужской пуховик и черный теплый свитер с оленями и рождественскими узорами',
		gender = 'male',
		warm = true,
	},
	winter6_sheet = {
		mat = 'models/humans/modern/octo/winter6_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Красный свитер с оленями (мужской)',
		desc = 'Теплый мужской красный свитер, на котором красуются олени и рождественские узоры',
		gender = 'male',
		warm = true,
	},
	winter7_sheet = {
		mat = 'models/humans/modern/octo/winter7_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Белый пуховик (мужской)',
		desc = 'Теплый мужской белый пуховик и голубые джинсы, белые кроссовки',
		gender = 'male',
		warm = true,
	},
	winter1_sheet_woman = {
		mat = 'models/humans/modern/octo/winter1_sheet_woman',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Красный свитер (женский)',
		desc = 'Теплый женский свитер красного цвета с рождественскими узорами',
		gender = 'female',
		warm = true,
	},
	winter2_sheet_woman = {
		mat = 'models/humans/modern/octo/winter2_sheet_woman',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Белый свитер (женский)',
		desc = 'Теплый женский свитер белого цвета с рождественскими узорами',
		gender = 'female',
		warm = true,
	},
	winter3_sheet_woman = {
		mat = 'models/humans/modern/octo/winter3_sheet_woman',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Зеленый свитер (женский)',
		desc = 'Теплый женский свитер зеленого цвета с милым оленем',
		gender = 'female',
		warm = true,
	},
	winter4_sheet_woman = {
		mat = 'models/humans/modern/octo/winter4_sheet_woman',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Розовый свитер (женский)',
		desc = 'Теплый женский свитер розового цвета с оленями и рождественскими узорами',
		gender = 'female',
		warm = true,
	},
	winter5_sheet_woman = {
		mat = 'models/humans/modern/octo/winter5_sheet_woman',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Черный пуховик (женский)',
		desc = 'Черный женский пуховик и белый теплый свитер, синие джинсы и черные ботинки',
		gender = 'female',
		warm = true,
	},

	-- halloween 2022
	halloween1_sheet = {
		mat = 'models/humans/modern/octo/halloween1_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Хэллоуинский свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween1_sheet_women = {
		mat = 'models/humans/modern/octo/halloween1_sheet_women',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Хэллоуинский свитер (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween2_sheet = {
		mat = 'models/humans/modern/octo/halloween2_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		desc = 'Тематический набор одежды, который дополнит праздник',
		name = 'Мрачный свитер (мужской)',
		gender = 'male'
	},
	halloween2_sheet_women = {
		mat = 'models/humans/modern/octo/halloween2_sheet_women',
		icon = octolib.icons.color('clothes_jumper'),
		desc = 'Тематический набор одежды, который дополнит праздник',
		name = 'Мрачный свитер (женский)',
		gender = 'female'
	},
	halloween3_sheet = {
		mat = 'models/humans/modern/octo/halloween3_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Жуткий свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween3_sheet_women = {
		mat = 'models/humans/modern/octo/halloween3_sheet_women',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Жуткий свитер (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween4_sheet = {
		mat = 'models/humans/modern/octo/halloween4_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Черный свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male'
	},
	halloween4_sheet_women = {
		mat = 'models/humans/modern/octo/halloween4_sheet_women',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Черный свитер (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female'
	},
	halloween5_sheet = {
		mat = 'models/humans/modern/octo/halloween5_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		desc = 'Тематический набор одежды, который дополнит праздник',
		name = 'Серый свитер (мужской)',
		gender = 'male'
	},
	halloween5_sheet_women = {
		mat = 'models/humans/modern/octo/halloween5_sheet_women',
		icon = octolib.icons.color('clothes_jumper'),
		desc = 'Тематический набор одежды, который дополнит праздник',
		name = 'Серый свитер (женский)',
		gender = 'female'
	},
	halloween6_sheet = {
		mat = 'models/humans/modern/octo/halloween6_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Забавный свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male'
	},
	halloween6_sheet_women = {
		mat = 'models/humans/modern/octo/halloween6_sheet_women',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Забавный свитер (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female'
	},
	halloween7_sheet = {
		mat = 'models/humans/modern/octo/halloween7_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Лама-вампир свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween7_sheet_women = {
		mat = 'models/humans/modern/octo/halloween7_sheet_women',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Лама-вампир свитер (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween8_sheet = {
		mat = 'models/humans/modern/octo/halloween8_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Свитер с рыжим котиком (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween8_sheet_women = {
		mat = 'models/humans/modern/octo/halloween8_sheet_women',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Свитер с рыжим котиком (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween9_sheet = {
		mat = 'models/humans/modern/octo/halloween9_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Зеленый свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male'
	},

	halloween11_sheet = {
		mat = 'models/humans/modern/octo/halloween11_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Тыквенный свитер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween11_sheet_women = {
		mat = 'models/humans/modern/octo/halloween11_sheet_women',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Тыквенный свитер (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},

	-- halloween 2023
	halloween12_sheet = {
		mat = 'models/humans/modern/octo/halloween12_sheet',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Свитер с кошкой (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween12_sheet_women = {
		mat = 'models/humans/modern/octo/halloween12_sheet_women',
		icon = octolib.icons.color('clothes_warm'),
		name = 'Свитер с хижиной (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween13_sheet = {
		mat = 'models/humans/modern/octo/halloween13_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Кожаный жакет (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween13_sheet_women = {
		mat = 'models/humans/modern/octo/halloween13_sheet_women',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Красная куртка (женская)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween14_sheet = {
		mat = 'models/humans/modern/octo/halloween14_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Тыквенная кофта (мужская)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween15_sheet = {
		mat = 'models/humans/modern/octo/halloween15_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Жуткий бомбер (мужской)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween16_sheet = {
		mat = 'models/humans/modern/octo/halloween16_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Кровавая жилетка (мужская)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},

	-- gentlemen
	gentlemen_sheet_1 = {
		mat = 'models/humans/modern/octo/gentlemen_sheet_1',
		icon = octolib.icons.color('tracksuit'),
		name = 'Зеленая спортивка (мужская)',
		desc = 'Будь на самом лучшем стиле!',
		gender = 'male',
		persistent = true,
	},
	gentlemen_sheet_2 = {
		mat = 'models/humans/modern/octo/gentlemen_sheet_2',
		icon = octolib.icons.color('tracksuit'),
		name = 'Синяя спортивка (мужская)',
		desc = 'Будь на самом лучшем стиле!',
		gender = 'male',
		persistent = true,
	},
	gentlemen_sheet_3 = {
		mat = 'models/humans/modern/octo/gentlemen_sheet_3',
		icon = octolib.icons.color('tracksuit'),
		name = 'Бежевая спортивка (мужская)',
		desc = 'Будь на самом лучшем стиле!',
		gender = 'male',
		persistent = true,
	},
	gentlemen_sheet_4 = {
		mat = 'models/humans/modern/octo/gentlemen_sheet_4',
		icon = octolib.icons.color('tracksuit'),
		name = 'Голубая спортивка (мужская)',
		desc = 'Будь на самом лучшем стиле!',
		gender = 'male',
		persistent = true,
	},
	gentlemen_sheet_5 = {
		mat = 'models/humans/modern/octo/gentlemen_sheet_5',
		icon = octolib.icons.color('tracksuit'),
		name = 'Красно-синяя спортивка (мужская)',
		desc = 'Будь на самом лучшем стиле!',
		gender = 'male',
		persistent = true,
	},
	gentlemen_sheet_6 = {
		mat = 'models/humans/modern/octo/gentlemen_sheet_6',
		icon = octolib.icons.color('tracksuit'),
		name = 'Красная спортивка (мужская)',
		desc = 'Будь на самом лучшем стиле!',
		gender = 'male',
		persistent = true,
	},

	-- winter 2023
	winter9_sheet = {
		name = 'Модный пуховик (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Пуховик модного бренда, синие джинсы и белые кроссовки',
		mat = 'models/humans/modern/octo/winter9_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter10_sheet = {
		name = 'Спортивный пуховик (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Бирюзовый пуховик со спортивной кофтой и черными штанами',
		mat = 'models/humans/modern/octo/winter10_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter11_sheet = {
		name = 'Утепленная дубленка (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Дубленка с белыми джинсами и шарфом',
		mat = 'models/humans/modern/octo/winter11_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter12_sheet = {
		name = 'Жилетка с красным свитером (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Темно-синяя жилетка с красным свитером',
		mat = 'models/humans/modern/octo/winter12_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter13_sheet = {
		name = 'Жилетка с зеленым свитером (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Светло-серая жилетка с зеленым свитером',
		mat = 'models/humans/modern/octo/winter13_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter14_sheet = {
		name = 'Теплый свитер (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Теплый красный рождественский свитер',
		mat = 'models/humans/modern/octo/winter14_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter6_sheet_woman = {
		name = 'Красная куртка (женская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Красная куртка с фиолетовым свитером',
		mat = 'models/humans/modern/octo/winter6_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter7_sheet_woman = {
		name = 'Шерстяная куртка с джемпером (женская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Белая шерстяная куртка, под которым красуется красный джемпер',
		mat = 'models/humans/modern/octo/winter7_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter8_sheet_woman = {
		name = 'Зеленый пуховик (женский)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Зеленый пуховик с серыми джинсами',
		mat = 'models/humans/modern/octo/winter8_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},

	-- winter 2024
	winter15_sheet = {
		name = 'Серое полупальто (мужское)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter15_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter16_sheet = {
		name = 'Синяя безрукавка (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter16_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter17_sheet = {
		name = 'Куртка с узорами (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter17_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter18_sheet = {
		name = 'Мультяшный свитер (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter18_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter19_sheet = {
		name = 'Черный пуховик (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter19_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter20_sheet = {
		name = 'Утепленная кожанка (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter20_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter9_sheet_woman = {
		name = 'Плюшевая куртка (женская)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter9_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter10_sheet_woman = {
		name = 'Клетчатое полупальто (женское)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter10_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter11_sheet_woman = {
		name = 'Свитер GhostBuster (женский)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter11_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter12_sheet_woman = {
		name = 'Синий пуховик (женский)',
		icon = octolib.icons.color('clothes_warm'),
		mat = 'models/humans/modern/octo/winter12_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},

	-- winter loot cases
	winter21_sheet = {
		name = 'Бежевый пуховик (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Теплеый бежевый пуховик',
		mat = 'models/humans/modern/octo/winter21_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter22_sheet = {
		name = 'Утепленная джинсовка (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Синяя теплая джинсовка с мехом',
		mat = 'models/humans/modern/octo/winter22_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter23_sheet = {
		name = 'Пуховик с патчем (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Зеленый пуховик с модным патчем',
		mat = 'models/humans/modern/octo/winter23_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter24_sheet = {
		name = 'Меховая куртка (мужская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Темно-синяя куртка с мехом',
		mat = 'models/humans/modern/octo/winter24_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter13_sheet_woman = {
		name = 'Зеленый пуховик (женский)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Модный зеленый зимний пуховик',
		mat = 'models/humans/modern/octo/winter13_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter15_sheet_woman = {
		name = 'Белая утепленная куртка (женская)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Зимняя утепленная куртка',
		mat = 'models/humans/modern/octo/winter15_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter25_sheet = {
		name = 'Эльфийский свитер (мужской)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Забавный зеленый свитер с костюмом эльфа',
		mat = 'models/humans/modern/octo/winter25_sheet',
		gender = 'male',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},
	winter14_sheet_woman = {
		name = 'Эльфийский свитер (женский)',
		icon = octolib.icons.color('clothes_warm'),
		desc = 'Забавный зеленый свитер с костюмом эльфа',
		mat = 'models/humans/modern/octo/winter14_sheet_woman',
		gender = 'female',
		mass = 0.5,
		volume = 2.5,
		warm = true,
		persistent = true,
	},

	-- ghetto
	ghetto01_sheet = {
		name = 'Свитер Kenzo (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Черный свитер, синий ремень и потертые джинсы',
		mat = 'models/humans/modern/octo/ghetto01_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto02_sheet = {
		name = 'Небесный худи (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Голубой худи, белый ремень и светлые джинсы',
		mat = 'models/humans/modern/octo/ghetto02_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto03_sheet = {
		name = 'Худи Amiri (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Красный худи и черные джинсы',
		mat = 'models/humans/modern/octo/ghetto03_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto04_sheet = {
		name = 'Худи Celine (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Серый худи и белые джинсы',
		mat = 'models/humans/modern/octo/ghetto04_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto05_sheet = {
		name = 'Спортивный худи (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Черный худи и черные джинсы в крапинку',
		mat = 'models/humans/modern/octo/ghetto05_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto06_sheet = {
		name = 'Худи Sp5der (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Черный худи и джинсы в крапинку',
		mat = 'models/humans/modern/octo/ghetto06_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto07_sheet = {
		name = 'Серый Amiri (мужской)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Серый худи, ремень и джинсы',
		mat = 'models/humans/modern/octo/ghetto07_sheet',
		gender = 'male',
		persistent = true,
	},
	ghetto08_sheet = {
		name = 'Кожанка с крестом (мужская)',
		icon = octolib.icons.color('tracksuit'),
		desc = 'Кожанка, бадлон и золотой крест',
		mat = 'models/humans/modern/octo/ghetto08_sheet',
		gender = 'male',
		persistent = true,
	},

	-- halloween 2024
	halloween17_sheet = {
		mat = 'models/humans/modern/octo/halloween17_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Черная косуха',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween18_sheet = {
		mat = 'models/humans/modern/octo/halloween18_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Свитер "Звонок"',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween19_sheet = {
		mat = 'models/humans/modern/octo/halloween19_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Жуткая джинсовка',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween20_sheet = {
		mat = 'models/humans/modern/octo/halloween20_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Хэллоуинский бомбер',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween21_sheet = {
		mat = 'models/humans/modern/octo/halloween21_sheet',
		icon = octolib.icons.color('clothes_coat'),
		name = 'Праздничный костюм',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween22_sheet = {
		mat = 'models/humans/modern/octo/halloween22_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Стильный худи',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'male',
		persistent = true,
	},
	halloween23_sheet = {
		mat = 'models/humans/modern/octo/halloween23_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Свитер с черепами',
		desc = 'Серый свитер с черепами и джинсами',
		gender = 'male',
		persistent = true,
	},
	halloween24_sheet = {
		mat = 'models/humans/modern/octo/halloween24_sheet',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Кожанка с паутиной',
		desc = 'Красная кожанка с паутиной',
		gender = 'male',
		persistent = true,
	},
	halloween26_sheet = {
		mat = 'models/humans/modern/octo/halloween26_sheet',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Свитер с тыквой',
		desc = 'Темный свитер с тыквой',
		gender = 'male',
		persistent = true,
	},
	halloween14_sheet_women = {
		mat = 'models/humans/modern/octo/halloween14_sheet_women',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Жуткий кардиган (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween15_sheet_women = {
		mat = 'models/humans/modern/octo/halloween15_sheet_women',
		icon = octolib.icons.color('clothes_jumper'),
		name = 'Костюм "Психоделика" (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},
	halloween16_sheet_women = {
		mat = 'models/humans/modern/octo/halloween16_sheet_women',
		icon = octolib.icons.color('clothes_jacket'),
		name = 'Джинсовка "Крик" (женский)',
		desc = 'Тематический набор одежды, который дополнит праздник',
		gender = 'female',
		persistent = true,
	},

	-- winter 2025
	winter26_sheet = {
		name = 'Чилловый свитер (мужской)',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'models/humans/modern/octo/winter26_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter27_sheet = {
		name = 'Куртка из шерпы (мужская)',
		icon = octolib.icons.color('clothes_jacket'),
		mat = 'models/humans/modern/octo/winter27_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter28_sheet = {
		name = 'Холщовое пальто (мужское)',
		icon = octolib.icons.color('clothes_coat'),
		mat = 'models/humans/modern/octo/winter28_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter29_sheet = {
		name = 'Шерстяное полупальто (мужское)',
		icon = octolib.icons.color('clothes_coat'),
		mat = 'models/humans/modern/octo/winter29_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter30_sheet = {
		name = 'Свитер "This is Fine" (мужской)',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'models/humans/modern/octo/winter30_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter31_sheet = {
		name = 'Жилетка со свитером (мужская)',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'models/humans/modern/octo/winter31_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter32_sheet = {
		name = 'Модный бомбер (мужской)',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'models/humans/modern/octo/winter32_sheet',
		desc = 'Теплая зимняя одежда',
		gender = 'male',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter16_sheet_woman = {
		name = 'Розовый пуховик (женский)',
		icon = octolib.icons.color('clothes_jacket'),
		mat = 'models/humans/modern/octo/winter16_sheet_woman',
		desc = 'Теплая зимняя одежда',
		gender = 'female',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},
	winter17_sheet_woman = {
		name = 'Чилловый свитер (женский)',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'models/humans/modern/octo/winter17_sheet_woman',
		desc = 'Теплая зимняя одежда',
		gender = 'female',
		mass = 1,
		volume = 1,
		warm = true,
		persistent = true,
	},

	-- nefor
	balenci = {
		name = 'Худи "Баленсиага"',
		icon = octolib.icons.color('clothes_hoodie'),
		mat = 'roscoe/clo/balenci',
		desc = 'Зеленый худи, черные джинсы и черно-белые кроссовки',
		gender = 'male',
		mass = 1,
		volume = 1,
		persistent = true,
	},
	erdblue = {
		name = 'Синяя кожанка',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'roscoe/clo/erdblue',
		desc = 'Синяя кожанка, черные джинсы и черно-белые кеды',
		gender = 'male',
		mass = 1,
		volume = 1,
		persistent = true,
	},
	erdred = {
		name = 'Красная джинсовка',
		icon = octolib.icons.color('clothes_jumper'),
		mat = 'roscoe/clo/erdred',
		desc = 'Красная джинсовка, бежевые штаны и коричневые ботинки',
		gender = 'male',
		mass = 1,
		volume = 1,
		persistent = true,
	},
	margiela = {
		name = 'Комбинированная рубашка',
		icon = octolib.icons.color('clothes_shirt'),
		mat = 'roscoe/clo/margiela',
		desc = 'Комбинированная рубашка, штаны с узором и черные кроссовки',
		gender = 'male',
		mass = 1,
		volume = 1,
		persistent = true,
	},
	numbernine = {
		name = 'Худи "NNSVC"',
		icon = octolib.icons.color('clothes_hoodie'),
		mat = 'roscoe/clo/numbernine',
		desc = 'Темный худи, синие джинсы и бежевые ботинки',
		gender = 'male',
		mass = 1,
		volume = 1,
		persistent = true,
	},
	vetements = {
		name = 'Худи "Vetemens"',
		icon = octolib.icons.color('clothes_hoodie'),
		mat = 'roscoe/clo/vetements',
		desc = 'Фиолетовый худи, потертые серые джинсы и черные кеды',
		gender = 'male',
		mass = 1,
		volume = 1,
		persistent = true,
	},
}

-- TODO: move to dbgChars.clothes
function dbgChars.getClothesItem(id)
	local data = CFG.clothes[id]
	if not data then
		error('Clothes with this ID is not registered: ' .. id)
	end

	return {'clothes_custom', {
		name = data.name,
		desc = data.desc,
		icon = data.icon,
		mass = data.mass,
		volume = data.volume,
		gender = data.gender or 'male',
		mat = data.mat,
		persistent = data.persistent,
	}}
end

local forbiddenSubmats = {}
for _, item in pairs(CFG.clothes) do
	forbiddenSubmats[item.mat] = true
end
hook.Add('submaterial.canUseOnPlayer', 'octoshop.donate-clothes', function(ply, target, mat)
	if forbiddenSubmats[mat] and not ply:IsAdmin() then
		return false
	end
end)
